name: jifog
favicon: null
layout_spectrum: 0.99773
typography_spectrum: 0.254
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F0EBF1'
    - '#040403'
    - '#EBD688'
    - '#797478'
    - '#A29CA2'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5125448
purpose: []
