collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8512545
  lightness: 0.5752688
  brandStrength: 1
  brandColors:
    - '#F0EBF1'
    - '#040403'
    - '#EBD688'
    - '#797478'
    - '#A29CA2'
  rhythmicContrast: 0.5125448
typography_spectrum: 0.3064516
layout_spectrum: 1
name: jifog
